# ==== CONFIGURE =====
# Use a Node base image using version 16-alpine
FROM

# Set the working directory to /app inside the container
WORKDIR

# ==== COPY ALL RELEVANT FILES =====
# Use this approach: COPY <source/path/on/local/machine> <destination/path/on/container/image/relative/to/workdir>
# First copy app folder to /app/app in the container
COPY

# Finally copy the specific files "package.json", "package-lock.json" and "tsconfig.json" to /app
# Hint: you can copy multiple files by listing as many sources you wish and ending with a destination path
COPY

# ==== BUILD =====
# Install dependencies and build with the same commands as you used locally
RUN 

# ==== RUN =======
# Start the app with the same command as you used locally
CMD 