# ==== DOCKERFILE FOR FRONTEND =====
# Use a Node 20 base image
FROM node:20-alpine

# Set the working directory to /app inside the container
WORKDIR /app

# Copy necessary source code folders/files
COPY app app
COPY [ "package.json", "package-lock.json", "tsconfig.json", "./"]

# ==== BUILD =====
# Install dependencies
RUN npm run build -- --no-lint
RUN npm run build

# ==== RUN =======
# Start the app
CMD [ "npm", "start" ]