# ==== CONFIGURE =====
# Use a Node 16 base image
FROM
# Set the working directory to /app inside the container
WORKDIR
# ==== COPY ALL RELEVANT FILES =====
# Use this approach: COPY <source/path/on/local/machine> <destination/path/on/container/image/relative/to/workdir>
# First copy src folder to /app/src in the container
COPY 
# Then copy public folder to /ap/public in the container
COPY
# Finally copy the specific files "package.json", "package-lock.json" and "tsconfig.json" to /app
# Hint: you can copy multiple files by listing as many sources you wish and ending with a destination path
COPY
# ==== BUILD =====
# Install dependencies with the same command as you used locally
RUN 
# ==== RUN =======
# Start the app with the same command as you used locally
CMD 